"""
Django settings for miproyecto project.
Generated by 'django-admin startproject' using Django 5.1.7.
"""

from pathlib import Path

# 📌 Rutas base del proyecto
BASE_DIR = Path(__file__).resolve().parent.parent

# 📌 Seguridad y configuración básica
SECRET_KEY = 'django-insecure-*1@xshxo38hy0b2^p-9-^-rm&o2+g$!wy6mh!04r27nce7b@vj'
DEBUG = True
ALLOWED_HOSTS = []

# 📌 Aplicaciones instaladas
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authapp',  # ✅ Nuestra aplicación personalizada
]

# 📌 Middlewares
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 📌 Configuración de URLs
ROOT_URLCONF = 'miproyecto.urls'

# 📌 Configuración de Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # ✅ Django buscará en templates/
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# 📌 Configuración de WSGI
WSGI_APPLICATION = 'miproyecto.wsgi.application'

# 📌 Base de datos (SQLite por defecto)
DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'miproyecto_db',  # Nombre de la base de datos en MongoDB
        'CLIENT': {
            'host': 'mongodb://localhost:27017/',  # Dirección de MongoDB
            'username': '',  # Si tienes autenticación, coloca tu usuario
            'password': '',  # Si tienes autenticación, coloca tu contraseña
            'authSource': 'admin',  # Base de datos donde está el usuario (deja "admin" si no cambiaste nada)
        }
    }
}

# 📌 Autenticación de Usuarios
AUTH_USER_MODEL = 'authapp.CustomUser'  # ✅ Ahora Django usará nuestro modelo de usuario personalizado

# 📌 Validación de contraseñas
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# 📌 Internacionalización
LANGUAGE_CODE = 'es'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# 📌 Archivos estáticos (CSS, JavaScript, Imágenes)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]  # ✅ Ahora Django sabrá dónde buscar archivos estáticos

# 📌 Configuración de archivos subidos por usuarios (Media)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# 📌 Configuración de campo de clave primaria por defecto
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'user_profile'  # Si no está definida otra redirección, irá a esta por defecto
LOGOUT_REDIRECT_URL = 'login'





