# Generated by Django 3.1.12 on 2025-03-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_auto_20250321_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('Admin', 'Administrador'), ('Normal', 'Usuario Normal')], default='Normal', max_length=10),
        ),
    ]
