# Generated by Django 3.1.12 on 2025-03-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_auto_20250324_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='matricula',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(default='Normal', max_length=10),
        ),
    ]
